plugins:
  - jekyll-remote-theme
remote_theme: zivong/jekyll-theme-hydure
title: dev-hana
tagline: 개발일지
author.name: Jieun Jang
cover: https://mblogthumb-phinf.pstatic.net/MjAxNzAzMTRfMjE3/MDAxNDg5NDU0MTYzOTEy.XP3CmDOTC_oB8gyhApi2cv0d1MB3gTVDZ_9BpP2IG2og.vyVsm6Aw7xtnmrPwPVTOGJG46RZYwCi1tK6uN0k-PBog.PNG.labanalog/%EB%8B%A8%EC%83%89%EB%B0%B0%EA%B2%BD%ED%99%94%EB%A9%B43.png?type=w800